# Generated by Django 2.0.1 on 2018-01-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('aadhar', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
